### ISSUE TITLE
Question about location coordinates

### ISSUE THREAD

**Issue by linjingmo** [Ita97/ICASSP2024_5G_pos_meas#1]
I am also using matlab to simulate related CFR information, but I encountered problems in the design of coordinates. How do you generate such base station and user coordinates?

**Comment by Ita97** [comment]
The simulation scenario is based on "site viewer". You can upload a OSM map and interact with it directly on MATLAB. The base station coordinates are taken considering the actual position in the area. Instead, the user coordinates are trajectories generated using "NMEA Generator".
